### ISSUE TITLE
Regression: animated gif are not animated anymore

### ISSUE THREAD

**Issue by huxi** [gobbledegook/creevey#41] opened 2024-02-20 21:05 UTC
Animated gif are not animated anymore in v1.5.6 on macOS 14.3.1.

Surprisingly, animated webp are now animated which wasn't the case until recently.

**Comment by gobbledegook** [comment] 2024-02-21 00:01
I'm not able to reproduce this. Is this for all animated gifs, or just certain files?

**Comment by gobbledegook** [comment] 2024-02-21 03:38
(animated webp was introduced as a feature in 1.5.4)

**Comment by huxi** [comment] 2024-02-21 07:16
I think it's happening for all gifs.

I kind of assumed that this must be a me-problem in some way but I have no idea how.

I'm using an M2 MacBook Air (2023) and this used to work until recently.

This gif is animated in Quick Look but isn't in Phoenix Slides. For me.

![Seinfeld](https://github.com/gobbledegook/creevey/assets/119647/a8fe0d17-cd82-4b26-97a6-5d45a6d71253)

**Comment by gobbledegook** [comment] 2024-02-21 07:32
well we have the same machine, system, and app versions, and jerry is waving his hands just fine for me... also the way gifs are animated is fundamentally unchanged since... whenever i introduced the feature, and it's similar to how webp's are animated...

do you have the same problem with this version?

https://blyt.net/phxslides/phoenix-slides-156d3.dmg

if so i can send you a version with some logging to try to see where it's failing...

**Comment by huxi** [comment] 2024-02-21 07:34
Yes, same issue.

**Comment by gobbledegook** [comment] 2024-02-24 01:39
Wait a minute... do you have "Show Large Images at Actual Size" turned on?

**Comment by gobbledegook** [comment] 2024-02-24 02:39
ok assuming that was the case, try this version to see if it fixes the issue:

https://blyt.net/phxslides/phoenix-slides-156d4.dmg

**Comment by huxi** [comment] 2024-02-24 09:53
Yes, that version works again!

**Comment by gobbledegook** [comment] 2024-02-27 07:48
fixed in 1.5.7

**Closed by gobbledegook** 2024-02-27 07:48 UTC
